### ISSUE TITLE
Is there a function that gets called when the user hits cancel?

### ISSUE THREAD

**Issue by wordyallen** [navjobs/upload#11]
I need to change state if the user hits cancel on the file dialog.

**Comment by zackify** [comment]
So there isn't a way you really know. If onFiles is still empty, nothing is
there. I do see how it could be useful if a user clicks the area, and hits
cancel on the dialog.

How about I add onCancel to the UploadField component for you? It will be
called if you click the dialog, and then cancel out of it.

**Comment by wordyallen** [comment]
that would be great!

**Comment by zackify** [comment]
I'll work on this tomorrow. Not 100% sure how to grab a cancel event from
that dialog but I'm sure there's a way.

**Comment by zackify** [comment]
http://stackoverflow.com/questions/11014384/cancel-file-upload-listener Looks like it's not really possible. onFiles would not be triggered until there are some files there. I don't get what your UI would need to do differently. Essentially it can just act as if the upload button was never clicked?

**Comment by zackify** [comment]
Going to close this for now, let me know if you need any help
