### ISSUE TITLE
Styling input[type=file]

### ISSUE THREAD

**Issue by damianobarbati** [navjobs/upload#18]
Probably due to the css framework or some resetter I have the input with the following styles:
```
    top: 0px;
    right: 0px;
    opacity: 0;
    width: 100%;
    height: 100%;
    cursor: pointer;
    position: absolute;
```
This means that wherever I click the upload is triggered.
How can I apply styles over the `<input/>`?

I tried with `<UploadField style={{ width: 0, height: 0 }}` without success.

**Comment by zackify** [comment]
Can you show your full code? Whatever components you have inside of `UploadField` will be clickable as a file input:

```js
import { UploadField } from '@navjobs/upload'

  <UploadField
    onFiles={files => //files object here}
    containerProps={{
      className: 'resume_import'
    }}
    uploadProps={{
      accept: '.pdf,.doc,.docx,.txt,.rtf',
    }}
  >
    <div>
      Click here to upload! This can be an image,
      or any component you can dream of.
    </div>
  </UploadField>
```

The div inside will be clickable everywhere. You should only place it around what you want clickable.

**Comment by damianobarbati** [comment]
Here's the code.
```
            <UploadField
                onFiles={([file]) => importXlsx(file)}
                uploadProps={{ accept: '.xlsx,.csv' }}
                containerProps={{ style: { boxShadow: '0px 1px 5px 0px rgba(0, 0, 0, 0.2), 0px 2px 2px 0px rgba(0, 0, 0, 0.14), 0px 3px 1px -2px rgba(0, 0, 0, 0.12)' } }}
            >
                <Button raised={true} onClick={() => console.log('ciao')}>Import</Button>
            </UploadField>
```

The button is rendered ok, here the screen with the computed final styles (input full screen, button is ok):
<img width="2048" alt="screen shot 2017-08-04 at 15 13 56" src="https://user-images.githubusercontent.com/2225869/28970130-ad7ba390-7927-11e7-9bbc-c974cca5331d.png">
<img width="2048" alt="screen shot 2017-08-04 at 15 14 06" src="https://user-images.githubusercontent.com/2225869/28970132-afafa36e-7927-11e7-911a-b56be3082bb3.png">

**Comment by zackify** [comment]
Ah, I think I see. The upload field spans 100% height and width. You need to wrap it inside of something that is constrained to the height and width of your button. So like:

```js
<div style={{width: '50px', height: '50px'}}>
<UploadField
    onFiles={files => //files object here}
    containerProps={{
      className: 'resume_import'
    }}
    uploadProps={{
      accept: '.pdf,.doc,.docx,.txt,.rtf',
    }}
  >
    <div>
      Click here to upload! This can be an image,
      or any component you can dream of.
    </div>
  </UploadField>
</div>
```

**Comment by damianobarbati** [comment]
Doh!

**Comment by zackify** [comment]
Let me know if you need any more help, I'll close this :)
