### ISSUE TITLE
TypeError: instance is not a function

### ISSUE THREAD

**Issue by nypinstripes** [navjobs/upload#23]
Hey, this seems like the most legit uploader lib i've seen so far, but i'm having a little trouble implementing the imperative API version in a redux action, maybe you can shed light on what I'm doing wrong or if there is actually an issue. When I run the UploadRequest on a file I get back this value for instance which is undefined.

<img width="576" alt="screen shot 2017-10-31 at 5 35 39 pm" src="https://user-images.githubusercontent.com/1851296/32250635-b49a3796-be63-11e7-8e5d-ad8c0050ff42.png">

Which logs the following error:

<img width="741" alt="screen shot 2017-10-31 at 5 44 52 pm" src="https://user-images.githubusercontent.com/1851296/32250641-c06c9fbe-be63-11e7-9d88-131878eb0e8b.png">

Here is what my call looks like:

![screen shot 2017-10-31 at 5 44 02 pm](https://user-images.githubusercontent.com/1851296/32250667-d759d70a-be63-11e7-8796-82461d92367a.png)

I've verified all the params url, hash, mimetype, auth etc.

This is for a multipart file uploader (for my work) and there aren't really a whole lot of other nice options to do this out there at the moment, so would love to get this very elegant one to work.

**Comment by zackify** [comment]
I’ll look into this first thing tomorrow, thanks for the report and glad
you like it :)

**Comment by zackify** [comment]
Sorry, stupid mistake from a while back, download the new release. Should work fine https://github.com/navjobs/upload/releases/tag/3.1.0

**Comment by nypinstripes** [comment]
Sweet "progress" @zackify humming along smooth now thanks.
