### ISSUE TITLE
UploadRequest resolves with error for 2xx status codes other then 200 and 201

### ISSUE THREAD

**Issue by jschlieber** [navjobs/upload#24]
## First things first
Thank you for sharing this great project. Really handy!

## Minor Issue
If e.g. I upload a file to S3, it returns a `204` which is not an error. Nevertheless `UploadRequest` will resolve to:
```
{
  error: true,
  response: "",
  status: 204
}
```

 Also there are a lot more `2xx` success statuses (https://httpstatuses.com/). I think you shouldn't set `error: true` for them either...

**Comment by zackify** [comment]
Haha yes that was a really bad mistake on my part. Will fix this today.

**Comment by zackify** [comment]
This should do it. Error if status is less than 200, or greater than / equal to 300 https://github.com/navjobs/upload/commit/157dc9a68df17b34bb83f3b8d543ac179e7d03b2
