### ISSUE TITLE
React 16 Upgrade

### ISSUE THREAD

**Issue by nypinstripes** [navjobs/upload#25]
Hey,

Been using the imperative API for a while now and it works great, just upgraded my app to react 16, tested it out and it runs very smoothly. Still have this dependancy warning from yarn though " > @navjobs/upload@3.1.1" has incorrect peer dependency "react@^15.3.1". It's the only package ive got left in my tree that has the warning, just wanted to say something about it.

cheers

**Comment by zackify** [comment]
Sorry about that, should be fixed in 3.1.2, comment back if not :)
