### ISSUE TITLE
Upload twice same file do not trigger upload

### ISSUE THREAD

**Issue by bionicvapourboy** [navjobs/upload#26]
- Upload a file with UploadField
- Wait for upload to complete
- Try to upload the same file

Expected result
Upload is triggered

Actual result
Upload is not triggered

Note:
If a new file is selected upload starts, maybe the issue is in the "onChange" handler of the file input field.

**Comment by zackify** [comment]
Every time a change occurs the onChange is triggered, if the file isn't changed, it's not going to happen. Why would you want to upload the same file twice? This seems out of the scope of the component, all it does is wrap an input and onChange, nothing special.

**Comment by bionicvapourboy** [comment]
My fault, I was trying to upload 2 file with the same name and content generated automatically in the same moment. When content or date changes upload triggers correctly.

**Comment by michaelpoltorak** [comment]
In my code I intercept the upload process to display a UI component before doing the upload request. Hence, the user may end up in a situation where it actually makes sense to upload the same file twice. 

Is it possible you could make re-uploading an option?

**Comment by zackify** [comment]
I'm not doing anything special, as you can see here. https://github.com/navjobs/upload/blob/master/src/upload-field.js#L25 

It simply calls onChange when something changes.

What your asking is the same as "I have an input field, I want onChange called again, even when nothing changes" 

A solution for you would be to store the files object, ex `onFiles={files => this.setState({files})}`

Now, when your ui component says there was a problem uploading, you can grab the files again from `this.state.files` and reupload them :)

Hope that helps! @michaelpoltorak

**Comment by michaelpoltorak** [comment]
@zackify I'm not sure I made my self entirely clear - my bad. 

What I need is that the value on the input be reset after an upload. It can be done by simply adding a handler that resets the value on click like this:

``<input
          type='file'
          onClick={(e) => {
            e.target.value = '';
          }
          onChange={(e) => ...}
/>``

How does that sound to you?

**Comment by zackify** [comment]
I see, how about this: https://github.com/navjobs/upload/releases/tag/3.1.3 Now you can add the onChange handler yourself! @ michaelpoltorak

**Comment by zackify** [comment]
@michaelpoltorak you can pass that through uploadProps on the component, ex `uploadProps={{onClick: () => blah}}` 👍

**Comment by michaelpoltorak** [comment]
@zackify: Perfect. And thanks.
