### ISSUE TITLE
Access the input ref

### ISSUE THREAD

**Issue by adrienharnay** [navjobs/upload#28]
Hey,

Thanks for this useful library!

I would like to add a listener on the input for `onDragEnter` and `onDragExit`. Would it be possible to accept a `inputRef` prop, which would be forwarded to the input?

I could make the PR if you would like.

Thanks in advance!

**Comment by zackify** [comment]
You can use uploadProps on the field. No need for refs. uploadProps={{onDragEnter}} etc

**Comment by adrienharnay** [comment]
Indeed, hadn't thought of that. Thanks!
