### ISSUE TITLE
Support multiple files at once

### ISSUE THREAD

**Issue by zackify** [navjobs/upload#6]
Currently, only the first file selected is sent, this library doesn't support multiple. I don't need this at the moment, so if anyone has ideas on how to add this in, let me know.

**Comment by dreamorosi** [comment]
You could support a [multiple](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/multiple) attribute on `<UploadField>` while in its declaration conditionally add it like this:

```js
let isMultiple = typeof this.props.multiple !== 'undefined';
<input
  ....
  multiple={isMultiple}
  ....
/>
```

Then append each selected file in the formData like this (not sure it's the best way to iterate a FileList)
```js
for (var i = 0; i < files.length; i++) {
  let file = files.item(i);
  formData.append(request.fileName || 'file', file);
}
```

The only drawback is that you send all the files in the same request, if you want to do separate requests and have also their respective progress I think it'd be better to work in `handleUpload()`. What do you think?

**Comment by zackify** [comment]
The first part can already be accomplished:

```js
<UploadField
    onFiles={files => //files object here}
    uploadProps={{
      multiple: true
    }}
  >
```

The reason I thought this would be harder is because I didn't realize you can append the same name multiple times to make it an array with FormData! This is actually really easy. I'll do this tonight. 
Thanks for the comment!

**Comment by zackify** [comment]
Closed! Pushed a release. Too easy :) https://github.com/navjobs/upload/commit/7415608c22acd0125de14fcd2bb87a2dd5828c8c
